kind: Namespace
apiVersion: v1
metadata:
  name: kubevirt-ip-helper
  labels:
    app: kubevirt-ip-helper
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubevirt-ip-helper
  namespace: kubevirt-ip-helper
  labels:
    app: kubevirt-ip-helper
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubevirt-ip-helper-read
  labels:
    app: kubevirt-ip-helper
rules:
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["list", "watch"]
- apiGroups: ["kubevirtiphelper.k8s.binbash.org"]
  resources:
  - ippools
  - ippools/status
  - virtualmachinenetworkconfigs
  - virtualmachinenetworkconfigs/status
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: ["kubevirt.io"]
  resources:
  - virtualmachines
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubevirt-ip-helper-read
  labels:
    app: kubevirt-ip-helper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubevirt-ip-helper-read
subjects:
- kind: ServiceAccount
  name: kubevirt-ip-helper
  namespace: kubevirt-ip-helper
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubevirt-ip-helper
  namespace: kubevirt-ip-helper
  labels:
    app: kubevirt-ip-helper
rules:
- apiGroups: [""]
  resources:
  - configmaps
  verbs:
    - get
    - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubevirt-ip-helper
  namespace: kubevirt-ip-helper
  labels:
    app: kubevirt-ip-helper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubevirt-ip-helper
subjects:
- kind: ServiceAccount
  name: kubevirt-ip-helper
  namespace: kubevirt-ip-helper
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubevirt-ip-helper-config
  namespace: kubevirt-ip-helper
data:
  logLevel: "Info"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubevirt-ip-helper
  name: kubevirt-ip-helper
  namespace: kubevirt-ip-helper
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kubevirt-ip-helper
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{ "interface":"eth1","name":"<NETWORKATTACHMENTDEFINITION_NAME>","namespace":"<NAMESPACE>" }]'
      labels:
        app: kubevirt-ip-helper
    spec:
      containers:
      - name: kubevirt-ip-helper
        image: <DOCKER_REGISTRY_URI>/kubevirt-ip-helper:latest
        command:
        - /bin/sh
        - '-ec'
        - |
          ip addr flush dev eth1
          ip addr add <IP_ADDRESS>/<CIDR_MASK> dev eth1
          /app/kubevirt-ip-helper
        env:
          - name: LOGLEVEL
            value: INFO
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          capabilities:
            add: 
              - NET_ADMIN
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: kubevirt-ip-helper
      terminationGracePeriodSeconds: 30